### ISSUE TITLE
`/emote list` doesn't work for specific user

### ISSUE THREAD

**Issue by solumath** [GrillBot/GrillBot.Services#11]
`/emote list` doesn't work for specific user. It shows statistic for whole server
![image](https://github.com/GrillBot/grillbot/assets/56552845/963a0279-a210-4fa7-aa1a-887c90aaffb1)

**Comment by Misha12** [comment]
Resolved in the https://github.com/GrillBot/grillbot/commit/c934d4e4124f98ebb4d186e761fdcb2d751425f4. 

![image](https://github.com/GrillBot/GrillBot.Services/assets/9041462/52c6b24a-5ce5-48b7-9063-bde139202b34)
